# Generated by Django 6.0.6 on 2026-07-01 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coeur', '0001_initial'),
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Portrait affiché sur la fiche publique (si le membre est visible).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='photo'),
        ),
    ]
