# Generated by Django 6.0.6 on 2026-07-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coeur', '0002_membre_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=200)),
                ('objet', models.TextField(blank=True, help_text='Tel que déclaré (figure sur le reçu fiscal).', verbose_name="objet de l'association")),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('code_postal', models.CharField(blank=True, max_length=16, verbose_name='code postal')),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('numero_rna', models.CharField(blank=True, max_length=20, verbose_name='n° RNA')),
                ('numero_siret', models.CharField(blank=True, max_length=20, verbose_name='SIRET')),
                ('article_cgi', models.CharField(default='200', max_length=20, verbose_name='article du CGI')),
                ('signataire_nom', models.CharField(blank=True, max_length=200, verbose_name='nom du signataire')),
                ('signataire_qualite', models.CharField(blank=True, help_text='Ex. président·e, trésorier·e.', max_length=120, verbose_name='qualité du signataire')),
            ],
            options={
                'verbose_name': "paramètres de l'association",
                'verbose_name_plural': "paramètres de l'association",
            },
        ),
    ]
