# Generated by Django 6.0.6 on 2026-07-01 16:10

import apps.common.stockage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coeur', '0003_parametresassociation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('qualite', models.CharField(help_text='Ex. président·e, trésorier·e, délégué·e.', max_length=120, verbose_name='qualité')),
                ('mention_delegation', models.CharField(blank=True, help_text='Ex. « en vertu de la délégation du bureau du 12/03/2026 ».', max_length=255, verbose_name='mention de délégation')),
                ('signature_image', models.ImageField(blank=True, help_text="Signature scannée (PNG/JPG). Optionnelle : à défaut, seuls le nom et la qualité s'affichent.", storage=apps.common.stockage.StockagePrive, upload_to='signatures/', verbose_name='image de signature')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='coeur.membre', verbose_name='membre associé')),
            ],
            options={
                'verbose_name': 'signataire',
                'verbose_name_plural': 'signataires',
                'ordering': ['nom'],
            },
        ),
    ]
