# Generated by Django 6.0.6 on 2026-07-02 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coeur', '0004_signataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='site_web',
            field=models.URLField(blank=True, verbose_name='site web'),
        ),
        migrations.CreateModel(
            name='LienReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseau', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('bluesky', 'Bluesky'), ('mastodon', 'Mastodon'), ('autre', 'Autre')], max_length=20, verbose_name='réseau')),
                ('url', models.URLField(verbose_name='adresse')),
                ('libelle', models.CharField(blank=True, help_text='Nom affiché si « Autre » (sinon le nom du réseau est utilisé).', max_length=80, verbose_name='libellé')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_reseaux', to='coeur.membre', verbose_name='membre')),
            ],
            options={
                'verbose_name': 'lien réseau social',
                'verbose_name_plural': 'liens réseaux sociaux',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
