# Generated by Django 6.0.6 on 2026-07-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coeur', '0005_membre_site_web_lienreseau'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='mis_en_avant',
            field=models.BooleanField(default=False, help_text='Membre mis en avant dans la vedette (accordéon) de la page association.', verbose_name='à la une'),
        ),
    ]
