# Generated by Django 6.0.6 on 2026-07-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coeur', '0006_membre_mis_en_avant'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresassociation',
            name='bic',
            field=models.CharField(blank=True, max_length=11, verbose_name='BIC'),
        ),
        migrations.AddField(
            model_name='parametresassociation',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='parametresassociation',
            name='mention_tva',
            field=models.CharField(blank=True, help_text='Ex. « TVA non applicable, art. 293 B du CGI » (association non assujettie).', max_length=200, verbose_name='mention de TVA'),
        ),
    ]
