# Generated by Django 6.0.8 on 2026-08-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coeur", "0008_membre_identite_compte_optionnel"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametresassociation",
            name="accroche",
            field=models.CharField(
                blank=True,
                default="le spectacle vivant, en pleine lumière.",
                help_text="Une ligne, sous le nom, en grand sur la page d'accueil.",
                max_length=120,
                verbose_name="accroche",
            ),
        ),
        migrations.AddField(
            model_name="parametresassociation",
            name="presentation",
            field=models.TextField(
                blank=True,
                default="L'Improliante est une association de spectacle vivant. Elle porte ses propres créations et accompagne les projets de ses membres.",
                help_text="Deux ou trois phrases. Affichées sur la page d'accueil et en tête de la page « L'association ».",
                verbose_name="présentation publique",
            ),
        ),
        migrations.AlterField(
            model_name="parametresassociation",
            name="objet",
            field=models.TextField(
                blank=True,
                help_text="Tel que déclaré (figure sur le reçu fiscal). À ne pas confondre avec la présentation publique : celui-ci est l'objet statutaire, en langue juridique, et il est imprimé sur les documents officiels.",
                verbose_name="objet de l'association",
            ),
        ),
    ]
