# Generated by Django 6.0.8 on 2026-08-28 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coeur", "0010_alter_parametresassociation_nom"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametresassociation",
            name="afficher_adresse_postale",
            field=models.BooleanField(
                default=False,
                help_text="L'adresse déclarée plus haut est souvent le domicile d'un membre : elle reste privée tant que cette case n'est pas cochée.",
                verbose_name="afficher l'adresse postale sur le site",
            ),
        ),
        migrations.AddField(
            model_name="parametresassociation",
            name="email_public",
            field=models.EmailField(
                blank=True,
                help_text="Affiché sur la page Contact. À distinguer de CONTACT_EMAIL (variable d'environnement), qui est la destination technique des messages du formulaire et n'est jamais montrée.",
                max_length=254,
                verbose_name="e-mail public",
            ),
        ),
        migrations.AddField(
            model_name="parametresassociation",
            name="telephone_public",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="téléphone public"
            ),
        ),
        migrations.CreateModel(
            name="ContactPublic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Ex. « Réservations », « Contact presse », « Présidence ».",
                        max_length=120,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True,
                        help_text="Facultatif : une fonction peut être publiée sans nommer personne.",
                        max_length=200,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="téléphone"
                    ),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ordre d'affichage"
                    ),
                ),
                (
                    "parametres",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts_publics",
                        to="coeur.parametresassociation",
                    ),
                ),
            ],
            options={
                "verbose_name": "contact public",
                "verbose_name_plural": "contacts publics",
                "ordering": ["ordre", "role"],
            },
        ),
    ]
