# Generated by Django 6.0.8 on 2026-08-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coeur", "0011_parametresassociation_afficher_adresse_postale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lienreseau",
            name="url",
            field=models.URLField(
                help_text="Le lien complet vers votre page sur ce réseau, par exemple https://www.instagram.com/mon-compte/ — pas un pseudonyme.",
                verbose_name="adresse du profil",
            ),
        ),
    ]
