# Generated by Django 6.0.6 on 2026-09-13 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coeur', '0014_signataire_par_defaut'),
        ('medias', '0002_media_hauteur_media_largeur_media_vignette_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrouillonPageArtiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('role_public', models.CharField(blank=True, help_text='Ex. « Comédienne, mise en scène » — affiché sur la fiche publique.', max_length=200, verbose_name='rôle public')),
                ('bio', models.TextField(blank=True, verbose_name='biographie')),
                ('site_web', models.URLField(blank=True, verbose_name='site web')),
                ('publie_le', models.DateTimeField(blank=True, null=True, verbose_name='publié le')),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brouillon_page', to='coeur.membre', verbose_name='membre')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='dernière modification par')),
                ('photo', models.ForeignKey(blank=True, help_text='Portrait affiché sur la fiche publique (si le membre est visible).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='photo')),
                ('publie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='publié par')),
            ],
            options={
                'verbose_name': 'brouillon de page artiste',
                'verbose_name_plural': 'brouillons de pages artistes',
            },
        ),
    ]
