# Generated by Django 6.0.6 on 2026-09-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coeur', '0015_brouillonpageartiste'),
    ]

    operations = [
        migrations.AddField(
            model_name='brouillonpageartiste',
            name='video_texte',
            field=models.TextField(blank=True, help_text="Quelques lignes pour situer l'extrait (facultatif).", verbose_name='à propos de la vidéo'),
        ),
        migrations.AddField(
            model_name='brouillonpageartiste',
            name='video_titre',
            field=models.CharField(blank=True, help_text='Sert de nom au bouton de lecture — « Lire la vidéo » seul ne dit rien.', max_length=150, verbose_name='titre de la vidéo'),
        ),
        migrations.AddField(
            model_name='brouillonpageartiste',
            name='video_youtube',
            field=models.CharField(blank=True, help_text="Identifiant de la vidéo, déduit de l'adresse que vous collez.", max_length=11, verbose_name='vidéo YouTube'),
        ),
        migrations.AddField(
            model_name='membre',
            name='video_texte',
            field=models.TextField(blank=True, help_text="Quelques lignes pour situer l'extrait (facultatif).", verbose_name='à propos de la vidéo'),
        ),
        migrations.AddField(
            model_name='membre',
            name='video_titre',
            field=models.CharField(blank=True, help_text='Sert de nom au bouton de lecture — « Lire la vidéo » seul ne dit rien.', max_length=150, verbose_name='titre de la vidéo'),
        ),
        migrations.AddField(
            model_name='membre',
            name='video_youtube',
            field=models.CharField(blank=True, help_text="Identifiant de la vidéo, déduit de l'adresse que vous collez.", max_length=11, verbose_name='vidéo YouTube'),
        ),
    ]
