# Generated by Django 6.0.6 on 2026-09-13 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coeur', '0016_brouillonpageartiste_video_texte_and_more'),
        ('medias', '0003_media_fichier_prive'),
    ]

    operations = [
        migrations.AddField(
            model_name='brouillonpageartiste',
            name='video_couverture',
            field=models.ForeignKey(blank=True, help_text='Image affichée avant le clic. À défaut, le bloc reste typographique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='couverture de la vidéo'),
        ),
        migrations.AddField(
            model_name='membre',
            name='video_couverture',
            field=models.ForeignKey(blank=True, help_text='Image affichée avant le clic. À défaut, le bloc reste typographique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='couverture de la vidéo'),
        ),
    ]
