# Generated by Django 6.0.6 on 2026-07-01 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('code_postal', models.CharField(blank=True, max_length=16, verbose_name='code postal')),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=32, verbose_name='téléphone')),
                ('siret', models.CharField(blank=True, max_length=20, verbose_name='SIRET')),
                ('numero_tva', models.CharField(blank=True, max_length=20, verbose_name='n° TVA intracommunautaire')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='numéro')),
                ('objet', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('date_validite', models.DateField(blank=True, null=True, verbose_name="valable jusqu'au")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('facture', 'Facturé')], default='brouillon', max_length=10)),
                ('conditions', models.TextField(blank=True, verbose_name='conditions / mentions')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='facturation.client')),
            ],
            options={
                'verbose_name': 'devis',
                'verbose_name_plural': 'devis',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='numéro')),
                ('objet', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(verbose_name="date d'émission")),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=10)),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='validée le')),
                ('mentions_legales', models.TextField(blank=True, verbose_name='mentions légales')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='facturation.client')),
                ('devis_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='facturation.devis', verbose_name="devis d'origine")),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='désignation')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='prix unitaire HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='taux de TVA (%)')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.devis')),
            ],
            options={
                'verbose_name': 'ligne de devis',
                'verbose_name_plural': 'lignes',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='désignation')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='prix unitaire HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='taux de TVA (%)')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture')),
            ],
            options={
                'verbose_name': 'ligne de facture',
                'verbose_name_plural': 'lignes',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
