# Generated by Django 6.0.6 on 2026-07-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'émission"),
        ),
    ]
