# Generated by Django 6.0.6 on 2026-07-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_alter_facture_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteurFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True, verbose_name='année')),
                ('dernier', models.PositiveIntegerField(default=0, verbose_name='dernier numéro attribué')),
            ],
            options={
                'verbose_name': 'compteur de factures',
                'verbose_name_plural': 'compteurs de factures',
                'ordering': ['-annee'],
            },
        ),
    ]
