# Generated by Django 6.0.6 on 2026-07-01 15:32

import apps.common.stockage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_compteurfacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='fichier',
            field=models.FileField(blank=True, storage=apps.common.stockage.StockagePrive, upload_to='factures/%Y/', verbose_name='PDF de la facture'),
        ),
    ]
