# Generated by Django 6.0.6 on 2026-07-01 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0004_facture_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='avoir_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avoirs', to='facturation.facture', verbose_name='avoir sur la facture'),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_piece',
            field=models.CharField(choices=[('facture', 'Facture'), ('avoir', 'Avoir')], default='facture', max_length=8, verbose_name='type de pièce'),
        ),
    ]
