# Generated by Django 6.0.6 on 2026-07-01 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coeur', '0004_signataire'),
        ('facturation', '0005_facture_avoir_de_facture_type_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='signataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coeur.signataire', verbose_name='signataire'),
        ),
        migrations.AddField(
            model_name='facture',
            name='signataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coeur.signataire', verbose_name='signataire'),
        ),
    ]
