# Generated by Django 6.0.6 on 2026-09-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0006_devis_signataire_facture_signataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='instantane',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name="instantané d'émission"),
        ),
    ]
