# Generated by Django 6.0.6 on 2026-09-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0007_facture_instantane'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lignedevis',
            constraint=models.CheckConstraint(condition=models.Q(('taux_tva__gte', 0), ('taux_tva__lte', 100)), name='facturation_lignedevis_taux_tva_entre_0_et_100', violation_error_message='Le taux de TVA doit être compris entre 0 et 100 %.'),
        ),
        migrations.AddConstraint(
            model_name='lignefacture',
            constraint=models.CheckConstraint(condition=models.Q(('taux_tva__gte', 0), ('taux_tva__lte', 100)), name='facturation_lignefacture_taux_tva_entre_0_et_100', violation_error_message='Le taux de TVA doit être compris entre 0 et 100 %.'),
        ),
    ]
