# Generated by Django 6.0.6 on 2026-09-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0008_lignedevis_facturation_lignedevis_taux_tva_entre_0_et_100_and_more'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='lignedevis',
            name='facturation_lignedevis_taux_tva_entre_0_et_100',
            constraint=models.CheckConstraint(condition=models.Q(('taux_tva__gte', 0), ('taux_tva__lte', 100)), name='facturation_lignedevis_taux_tva_entre_0_et_100', violation_error_message='Le taux de TVA doit être compris entre 0 et 100 %%.'),
        ),
        migrations.AlterConstraint(
            model_name='lignefacture',
            name='facturation_lignefacture_taux_tva_entre_0_et_100',
            constraint=models.CheckConstraint(condition=models.Q(('taux_tva__gte', 0), ('taux_tva__lte', 100)), name='facturation_lignefacture_taux_tva_entre_0_et_100', violation_error_message='Le taux de TVA doit être compris entre 0 et 100 %%.'),
        ),
    ]
