# Generated by Django 6.0.6 on 2026-07-01 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'dossier',
                'verbose_name_plural': 'dossiers',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/', verbose_name='fichier')),
                ('description', models.TextField(blank=True)),
                ('confidentialite', models.CharField(choices=[('prive', 'Privé'), ('membres', 'Membres'), ('public', 'Public')], default='prive', max_length=8, verbose_name='confidentialité')),
                ('version', models.PositiveIntegerField(default=1)),
                ('courant', models.BooleanField(default=True, verbose_name='version courante')),
                ('date_validite', models.DateField(blank=True, null=True, verbose_name='date de validité')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_ajoutes', to=settings.AUTH_USER_MODEL, verbose_name='ajouté par')),
                ('remplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_suivantes', to='documents.document', verbose_name='remplace la version')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.dossier')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['titre', '-version'],
            },
        ),
    ]
