# Generated by Django 6.0.6 on 2026-07-01 14:33

import apps.common.stockage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(storage=apps.common.stockage.StockagePrive, upload_to='documents/%Y/%m/', verbose_name='fichier'),
        ),
    ]
