# Generated by Django 6.0.6 on 2026-07-05 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coeur', '0007_parametresassociation_bic_parametresassociation_iban_and_more'),
        ('documents', '0002_alter_document_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='proprietaire',
            field=models.ForeignKey(blank=True, help_text="Vide = dossier de l'association (GED gérée par le bureau).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='coeur.membre', verbose_name='propriétaire'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='visibilite',
            field=models.CharField(choices=[('prive', 'Privé (moi seul)'), ('partage', 'Partagé (toute la troupe)'), ('bureau', 'Transmis au bureau')], default='prive', help_text="Ne s'applique qu'aux dossiers d'un membre.", max_length=8, verbose_name='visibilité'),
        ),
    ]
