# Generated by Django 6.0.6 on 2026-07-05 18:43

import django.db.models.deletion
from django.db import migrations, models


def backfill_espace(apps, schema_editor):
    """Les dossiers existants avec un propriétaire sont personnels ; les autres
    restent « association » (valeur par défaut du nouveau champ)."""
    Dossier = apps.get_model("documents", "Dossier")
    Dossier.objects.filter(proprietaire__isnull=False).update(espace="perso")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('coeur', '0007_parametresassociation_bic_parametresassociation_iban_and_more'),
        ('documents', '0003_dossier_proprietaire_dossier_visibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='espace',
            field=models.CharField(choices=[('perso', 'Personnel'), ('commun', 'Commun (troupe)'), ('association', 'Association (bureau)')], default='association', help_text='Personnel (membre), commun (troupe) ou association (bureau).', max_length=12),
        ),
        migrations.RunPython(backfill_espace, noop),
        migrations.AlterField(
            model_name='dossier',
            name='proprietaire',
            field=models.ForeignKey(blank=True, help_text="Renseigné uniquement pour l'espace personnel d'un membre.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='coeur.membre', verbose_name='propriétaire'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='visibilite',
            field=models.CharField(choices=[('prive', 'Privé (moi seul)'), ('partage', 'Partagé (toute la troupe)'), ('bureau', 'Transmis au bureau')], default='prive', help_text="Ne s'applique qu'aux dossiers personnels d'un membre.", max_length=8, verbose_name='visibilité'),
        ),
    ]
