# Generated by Django 6.0.6 on 2026-09-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_dossier_espace_alter_dossier_proprietaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='confidentialite',
            field=models.CharField(choices=[('prive', 'Privé'), ('membres', 'Membres'), ('public', 'Tout compte connecté')], default='prive', help_text='Qui peut télécharger ce document une fois connecté. Aucun niveau ne le met en ligne : « Tout compte connecté » reste fermé aux visiteurs.', max_length=8, verbose_name='confidentialité'),
        ),
    ]
