# Generated by Django 6.0.6 on 2026-07-01 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo (lien externe)')], default='image', max_length=10, verbose_name='type')),
                ('fichier', models.ImageField(blank=True, help_text='Pour un média de type image.', upload_to='medias/%Y/%m/', verbose_name='fichier image')),
                ('url_externe', models.URLField(blank=True, help_text='Pour une vidéo : URL YouTube ou Vimeo.', verbose_name='lien vidéo')),
                ('alt', models.CharField(help_text="Obligatoire (accessibilité) : décrit le média pour les lecteurs d'écran.", max_length=255, verbose_name='texte alternatif')),
                ('legende', models.CharField(blank=True, max_length=255, verbose_name='légende')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='ajouté le')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias_ajoutes', to=settings.AUTH_USER_MODEL, verbose_name='ajouté par')),
            ],
            options={
                'verbose_name': 'média',
                'verbose_name_plural': 'médias',
                'ordering': ['-date_creation'],
            },
        ),
    ]
