# Generated by Django 6.0.6 on 2026-09-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='hauteur',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='hauteur (px)'),
        ),
        migrations.AddField(
            model_name='media',
            name='largeur',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='largeur (px)'),
        ),
        migrations.AddField(
            model_name='media',
            name='vignette',
            field=models.ImageField(blank=True, editable=False, upload_to='medias/vignettes/%Y/%m/', verbose_name='vignette'),
        ),
        migrations.AddField(
            model_name='media',
            name='vignette_hauteur',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='vignette_largeur',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
