# Generated by Django 6.0.6 on 2026-09-13 15:54

import apps.common.stockage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_media_hauteur_media_largeur_media_vignette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='fichier_prive',
            field=models.ImageField(blank=True, editable=False, storage=apps.common.stockage.StockagePrive, upload_to='brouillons/%Y/%m/', verbose_name='fichier image (brouillon)'),
        ),
    ]
