# Generated by Django 6.0.6 on 2026-07-01 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coeur', '0002_membre_photo'),
        ('medias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('statut_moderation', models.CharField(choices=[('brouillon', 'Brouillon'), ('propose', 'Proposé'), ('publie', 'Publié'), ('refuse', 'Refusé')], default='brouillon', max_length=12, verbose_name='statut de modération')),
                ('motif_refus', models.TextField(blank=True, verbose_name='motif de refus')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
                ('titre', models.CharField(max_length=200)),
                ('synopsis', models.TextField(blank=True)),
                ('note_intention', models.TextField(blank=True, verbose_name="note d'intention")),
                ('type_portage', models.CharField(choices=[('association', "Production de l'association"), ('personnel', "Projet personnel d'un membre"), ('collectif', 'Projet collectif')], default='association', max_length=12, verbose_name='type de portage')),
                ('statut_projet', models.CharField(choices=[('en_creation', 'En création'), ('en_repetition', 'En répétition'), ('a_l_affiche', "À l'affiche"), ('archive', 'Archivé')], default='en_creation', max_length=14)),
                ('metteur_en_scene_externe', models.CharField(blank=True, help_text="Si la mise en scène n'est pas assurée par un membre.", max_length=200, verbose_name='metteur·euse en scène (externe)')),
                ('duree_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée (minutes)')),
                ('genre', models.CharField(blank=True, max_length=120)),
                ('public_vise', models.CharField(blank=True, max_length=120, verbose_name='public visé')),
                ('affiche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='affiche')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('metteur_en_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mises_en_scene', to='coeur.membre', verbose_name='metteur·euse en scène (membre)')),
                ('porteurs', models.ManyToManyField(blank=True, help_text='Surtout pour les projets personnels ou collectifs.', related_name='spectacles_portes', to='coeur.membre', verbose_name='porteurs')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_valides', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'spectacle / projet',
                'verbose_name_plural': 'spectacles / projets',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='LigneDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_externe', models.CharField(blank=True, max_length=200, verbose_name='intervenant·e extérieur·e')),
                ('role', models.CharField(help_text='Ex. comédien·ne, mise en scène, technique, musique…', max_length=200, verbose_name='rôle')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles_distribution', to='coeur.membre', verbose_name='membre')),
                ('spectacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='spectacles.spectacle')),
            ],
            options={
                'verbose_name': 'ligne de distribution',
                'verbose_name_plural': 'distribution',
                'ordering': ['ordre', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('membre__isnull', False), ('nom_externe', '')), models.Q(('membre__isnull', True), models.Q(('nom_externe', ''), _negated=True)), _connector='OR'), name='distribution_membre_ou_nom_externe', violation_error_message="Renseignez soit un membre, soit un nom externe (exactement l'un des deux).")],
            },
        ),
        migrations.CreateModel(
            name='ImageSpectacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='medias.media')),
                ('spectacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spectacles.spectacle')),
            ],
            options={
                'verbose_name': 'image de la galerie',
                'verbose_name_plural': 'galerie',
                'ordering': ['ordre', 'id'],
                'constraints': [models.UniqueConstraint(fields=('spectacle', 'media'), name='image_spectacle_unique')],
            },
        ),
    ]
