# Generated by Django 6.0.6 on 2026-07-11 05:56

from django.db import migrations


def metteur_en_scene_vers_distribution(apps, schema_editor):
    """Reporte l'ancienne mise en scène dédiée dans la distribution.

    Chaque `Spectacle` qui avait un `metteur_en_scene` (membre) et/ou un
    `metteur_en_scene_externe` (texte) reçoit une ligne de distribution
    « Mise en scène » équivalente, ajoutée à la fin de sa distribution. On ne
    perd donc aucune information et les fiches membres gardent leurs
    « collaborations » (filtrées désormais sur la seule distribution).
    """
    Spectacle = apps.get_model("spectacles", "Spectacle")
    LigneDistribution = apps.get_model("spectacles", "LigneDistribution")
    db = schema_editor.connection.alias

    for spectacle in Spectacle.objects.using(db).all():
        ordre = LigneDistribution.objects.using(db).filter(spectacle=spectacle).count()
        if spectacle.metteur_en_scene_id:
            LigneDistribution.objects.using(db).create(
                spectacle=spectacle,
                membre_id=spectacle.metteur_en_scene_id,
                role="Mise en scène",
                ordre=ordre,
            )
            ordre += 1
        externe = (spectacle.metteur_en_scene_externe or "").strip()
        if externe:
            LigneDistribution.objects.using(db).create(
                spectacle=spectacle,
                nom_externe=externe,
                role="Mise en scène",
                ordre=ordre,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('spectacles', '0001_initial'),
    ]

    operations = [
        # Migration de données AVANT la suppression des colonnes : à ce point les
        # champs metteur_en_scene* existent encore sur le modèle historique.
        migrations.RunPython(
            metteur_en_scene_vers_distribution,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='spectacle',
            name='metteur_en_scene',
        ),
        migrations.RemoveField(
            model_name='spectacle',
            name='metteur_en_scene_externe',
        ),
    ]
