# Generated by Django 6.0.6 on 2026-07-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectacles', '0002_remove_spectacle_metteur_en_scene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectacle',
            name='modifie_apres_publication',
            field=models.BooleanField(default=False, help_text="L'auteur a retouché la fiche après sa mise en ligne : à revoir par le bureau (contrôle a posteriori). Les changements sont déjà publiés.", verbose_name='modifié depuis la publication'),
        ),
    ]
