# Generated by Django 6.0.6 on 2026-07-01 08:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('coeur', '0002_membre_photo'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresGouvernance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_reserve_aux_membres_a_jour', models.BooleanField(default=True, help_text='Valeur par défaut prudente — à ajuster selon les statuts.', verbose_name='vote réservé aux membres à jour de cotisation')),
                ('max_pouvoirs_par_personne', models.PositiveIntegerField(default=2, verbose_name='nombre max de pouvoirs par personne')),
                ('quorum_ag_ordinaire', models.DecimalField(decimal_places=3, default=Decimal('0.333'), max_digits=4, verbose_name='quorum AG ordinaire')),
                ('quorum_ag_extraordinaire', models.DecimalField(decimal_places=3, default=Decimal('0.500'), max_digits=4, verbose_name='quorum AG extraordinaire')),
                ('majorite_simple', models.DecimalField(decimal_places=3, default=Decimal('0.500'), max_digits=4, verbose_name='majorité simple')),
                ('majorite_qualifiee', models.DecimalField(decimal_places=3, default=Decimal('0.667'), max_digits=4, verbose_name='majorité qualifiée')),
            ],
            options={
                'verbose_name': 'paramètres de gouvernance',
                'verbose_name_plural': 'paramètres de gouvernance',
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('titre', models.CharField(max_length=200)),
                ('type_reunion', models.CharField(choices=[('ag_ordinaire', 'AG ordinaire'), ('ag_extraordinaire', 'AG extraordinaire'), ('bureau', 'Réunion de bureau')], max_length=18, verbose_name='type')),
                ('statut', models.CharField(choices=[('preparation', 'Préparation'), ('convoquee', 'Convoquée'), ('tenue', 'Tenue'), ('archivee', 'Archivée')], default='preparation', max_length=12)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('lieu_texte', models.CharField(blank=True, max_length=255, verbose_name='lieu')),
                ('convocation_texte', models.TextField(blank=True, verbose_name='texte de convocation')),
                ('date_convocation', models.DateField(blank=True, null=True, verbose_name="date d'envoi de la convocation")),
                ('compte_rendu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions_pv', to='documents.document', verbose_name='compte-rendu (PV)')),
                ('documents', models.ManyToManyField(blank=True, related_name='reunions', to='documents.document', verbose_name='documents joints')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions', to='agenda.evenement', verbose_name='événement agenda')),
            ],
            options={
                'verbose_name': 'réunion / AG',
                'verbose_name_plural': 'réunions / AG',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('propose', 'Proposé'), ('ouvert', 'Ouvert'), ('ordre_du_jour', "À l'ordre du jour"), ('traite', 'Traité'), ('reporte', 'Reporté'), ('refuse', 'Refusé')], default='propose', max_length=14)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute')], default='normale', max_length=8, verbose_name='priorité')),
                ('categorie', models.CharField(blank=True, max_length=120, verbose_name='catégorie')),
                ('motif_refus', models.TextField(blank=True, verbose_name='motif de refus')),
                ('ordre_du_jour', models.PositiveIntegerField(default=0, verbose_name="position à l'ordre du jour")),
                ('date', models.DateField(blank=True, null=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='sujets', to='documents.document', verbose_name='documents liés')),
                ('fusionne_dans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujets_fusionnes', to='gouvernance.sujet', verbose_name='fusionné dans')),
                ('propose_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujets_proposes', to='coeur.membre', verbose_name='proposé par')),
                ('reunion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujets', to='gouvernance.reunion', verbose_name='réunion (ordre du jour)')),
            ],
            options={
                'verbose_name': 'sujet',
                'verbose_name_plural': 'sujets',
                'ordering': ['-priorite', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('intitule', models.CharField(max_length=300, verbose_name='intitulé')),
                ('texte', models.TextField(blank=True)),
                ('type_majorite', models.CharField(choices=[('simple', 'Majorité simple'), ('qualifiee', 'Majorité qualifiée'), ('unanimite', 'Unanimité')], default='simple', max_length=10, verbose_name='type de majorité')),
                ('nombre_pour', models.PositiveIntegerField(default=0, verbose_name='pour')),
                ('nombre_contre', models.PositiveIntegerField(default=0, verbose_name='contre')),
                ('nombre_abstention', models.PositiveIntegerField(default=0, verbose_name='abstention')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='gouvernance.reunion')),
                ('sujet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions', to='gouvernance.sujet')),
            ],
            options={
                'verbose_name': 'résolution',
                'verbose_name_plural': 'résolutions',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('excuse', 'Excusé'), ('represente', 'Représenté'), ('absent', 'Absent')], default='absent', max_length=12)),
                ('peut_voter', models.BooleanField(default=False, help_text="Figé à la date de l'AG (ne pas recalculer rétroactivement).", verbose_name='droit de vote')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='coeur.membre')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='gouvernance.reunion')),
            ],
            options={
                'verbose_name': 'présence',
                'verbose_name_plural': 'présences',
                'constraints': [models.UniqueConstraint(fields=('reunion', 'membre'), name='presence_unique_par_membre')],
            },
        ),
        migrations.CreateModel(
            name='Pouvoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pouvoirs_donnes', to='coeur.membre', verbose_name='mandant (absent)')),
                ('mandataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pouvoirs_recus', to='coeur.membre', verbose_name='mandataire (présent)')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pouvoirs', to='gouvernance.reunion')),
            ],
            options={
                'verbose_name': 'pouvoir',
                'verbose_name_plural': 'pouvoirs',
                'constraints': [models.UniqueConstraint(fields=('reunion', 'mandant'), name='pouvoir_unique_par_mandant'), models.CheckConstraint(condition=models.Q(('mandant', models.F('mandataire')), _negated=True), name='pouvoir_mandant_distinct_mandataire', violation_error_message='Le mandant et le mandataire doivent être différents.')],
            },
        ),
    ]
