# Generated by Django 6.0.6 on 2026-07-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sujet',
            options={'ordering': ['-priorite', '-date', '-id'], 'verbose_name': 'sujet', 'verbose_name_plural': 'sujets'},
        ),
        migrations.AlterField(
            model_name='sujet',
            name='priorite',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Basse'), (2, 'Normale'), (3, 'Haute')], default=2, verbose_name='priorité'),
        ),
    ]
