# Generated by Django 6.0.6 on 2026-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0002_alter_sujet_options_alter_sujet_priorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresgouvernance',
            name='base_majorite',
            field=models.CharField(choices=[('exprimes', 'Suffrages exprimés (hors abstentions)'), ('presents', 'Présents/représentés (abstentions comprises)')], default='exprimes', help_text='Dénominateur des votes : exprimés (hors abstentions) ou présents/représentés.', max_length=10, verbose_name='base de la majorité'),
        ),
    ]
