# Generated by Django 6.0.6 on 2026-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0003_parametresgouvernance_base_majorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='compte_rendu_texte',
            field=models.TextField(blank=True, help_text='Notes générales de séance ; le PV est ensuite généré à partir de ces notes + présences, pouvoirs, quorum et résolutions.', verbose_name='synthèse du compte-rendu'),
        ),
        migrations.AddField(
            model_name='sujet',
            name='notes',
            field=models.TextField(blank=True, help_text='Ce qui a été dit ou décidé sur ce point (repris dans le PV).', verbose_name='notes / décision'),
        ),
    ]
