# Generated by Django 6.0.6 on 2026-07-13 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0004_reunion_compte_rendu_texte_sujet_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocCompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='intertitre')),
                ('texte', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('apres_sujet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocs_apres', to='gouvernance.sujet', verbose_name='placé après le point')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='gouvernance.reunion')),
            ],
            options={
                'verbose_name': 'bloc de compte-rendu',
                'verbose_name_plural': 'blocs de compte-rendu',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
