# Generated by Django 6.0.6 on 2026-09-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0005_bloccompterendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='regles_figees',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='règles figées à la clôture'),
        ),
    ]
