# Generated by Django 6.0.6 on 2026-07-01 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coeur', '0002_membre_photo'),
        ('medias', '0001_initial'),
        ('spectacles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('statut_moderation', models.CharField(choices=[('brouillon', 'Brouillon'), ('propose', 'Proposé'), ('publie', 'Publié'), ('refuse', 'Refusé')], default='brouillon', max_length=12, verbose_name='statut de modération')),
                ('motif_refus', models.TextField(blank=True, verbose_name='motif de refus')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField(verbose_name='début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('lieu_texte', models.CharField(blank=True, max_length=255, verbose_name='lieu (texte libre)')),
                ('visibilite', models.CharField(choices=[('public', 'Public'), ('membres', 'Membres'), ('interne', 'Interne')], default='public', max_length=8, verbose_name='visibilité')),
                ('affiche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medias.media', verbose_name='affiche')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('lieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='coeur.lieu', verbose_name='lieu (fiche)')),
                ('spectacle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representations', to='spectacles.spectacle', verbose_name='représentation de')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_valides', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Ex. organisateur·rice, participant·e…', max_length=120, verbose_name='rôle')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='agenda.evenement')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='coeur.membre')),
            ],
            options={
                'verbose_name': 'intervenant·e',
                'verbose_name_plural': 'intervenants',
            },
        ),
        migrations.AddField(
            model_name='evenement',
            name='intervenants',
            field=models.ManyToManyField(blank=True, related_name='evenements', through='agenda.Intervention', to='coeur.membre', verbose_name='intervenants'),
        ),
        migrations.CreateModel(
            name='ImageEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agenda.evenement')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='medias.media')),
            ],
            options={
                'verbose_name': 'image de la galerie',
                'verbose_name_plural': 'galerie',
                'ordering': ['ordre', 'id'],
                'constraints': [models.UniqueConstraint(fields=('evenement', 'media'), name='image_evenement_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='intervention',
            constraint=models.UniqueConstraint(fields=('evenement', 'membre'), name='intervention_unique'),
        ),
    ]
