# Generated by Django 6.0.8 on 2026-08-28 20:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_evenement_modifie_apres_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="places_max",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Laisser vide pour ne pas ouvrir d'inscription. Renseigné, le public peut réserver jusqu'à épuisement de la jauge.",
                null=True,
                verbose_name="nombre de places",
            ),
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="adresse e-mail"),
                ),
                (
                    "places",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="nombre de places"
                    ),
                ),
                (
                    "jeton",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="jeton",
                    ),
                ),
                ("annulee", models.BooleanField(default=False, verbose_name="annulée")),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="agenda.evenement",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscription",
                "verbose_name_plural": "inscriptions",
                "ordering": ["-date_creation"],
            },
        ),
    ]
