# Generated by Django 6.0.6 on 2026-07-01 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coeur', '0002_membre_photo'),
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='fin')),
            ],
            options={
                'verbose_name': 'saison',
                'verbose_name_plural': 'saisons',
                'ordering': ['-date_debut', '-nom'],
            },
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('payee', 'Payé'), ('exoneree', 'Exonéré'), ('en_attente', 'En attente')], default='en_attente', max_length=10)),
                ('montant_attendu', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='montant attendu')),
                ('montant_verse', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='montant versé')),
                ('date', models.DateField(blank=True, null=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesions', to='coeur.membre')),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesions', to='budget.saison')),
            ],
            options={
                'verbose_name': 'adhésion',
                'verbose_name_plural': 'adhésions',
                'ordering': ['-saison__date_debut', 'membre'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('type_flux', models.CharField(choices=[('recette', 'Recette'), ('depense', 'Dépense')], max_length=8, verbose_name='type')),
                ('statut', models.CharField(choices=[('prevu', 'Prévu'), ('realise', 'Réalisé')], default='prevu', max_length=8)),
                ('libelle', models.CharField(max_length=200, verbose_name='libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('adhesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget.adhesion')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget.categorie')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='facturation.facture')),
                ('saison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget.saison')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='adhesion',
            constraint=models.UniqueConstraint(fields=('membre', 'saison'), name='adhesion_unique_membre_saison'),
        ),
    ]
