# Generated by Django 6.0.6 on 2026-07-01 15:18

import apps.common.stockage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('coeur', '0003_parametresassociation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteurRecu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True, verbose_name='année')),
                ('dernier', models.PositiveIntegerField(default=0, verbose_name='dernier numéro attribué')),
            ],
            options={
                'verbose_name': 'compteur de reçus fiscaux',
                'verbose_name_plural': 'compteurs de reçus fiscaux',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='RecuFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='numéro')),
                ('date_emission', models.DateField(verbose_name="date d'émission")),
                ('type_versement', models.CharField(choices=[('don', 'Don'), ('cotisation', 'Cotisation')], max_length=12, verbose_name='type de versement')),
                ('forme', models.CharField(choices=[('numeraire', 'Numéraire'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('autre', 'Autre')], default='numeraire', max_length=12, verbose_name='forme du don')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_versement', models.DateField(verbose_name='date du versement')),
                ('donateur_nom', models.CharField(max_length=200, verbose_name='nom du donateur')),
                ('donateur_adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('donateur_code_postal', models.CharField(blank=True, max_length=16, verbose_name='code postal')),
                ('donateur_ville', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('fichier', models.FileField(blank=True, storage=apps.common.stockage.StockagePrive, upload_to='recus/%Y/', verbose_name='PDF du reçu')),
                ('adhesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_fiscaux', to='budget.adhesion')),
                ('emis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_emis', to=settings.AUTH_USER_MODEL, verbose_name='émis par')),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_fiscaux', to='coeur.membre', verbose_name='membre concerné')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_fiscaux', to='budget.transaction', verbose_name='transaction (don)')),
            ],
            options={
                'verbose_name': 'reçu fiscal',
                'verbose_name_plural': 'reçus fiscaux',
                'ordering': ['-date_emission', '-id'],
            },
        ),
    ]
