# Generated by Django 6.0.6 on 2026-07-01 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_compteurrecu_recufiscal'),
        ('coeur', '0004_signataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='recufiscal',
            name='signataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coeur.signataire', verbose_name='signataire'),
        ),
    ]
