# Generated by Django 6.0.6 on 2026-07-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_recufiscal_signataire'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldeTresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='solde en banque')),
                ('date_pointage', models.DateField(blank=True, null=True, verbose_name='date du pointage')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
            ],
            options={
                'verbose_name': 'solde de trésorerie',
                'verbose_name_plural': 'solde de trésorerie',
            },
        ),
    ]
